title: Welcome to my Page
description: I am an engineer by training. I work as a Research Assistant at CVPR Unit, Indian Statistical Institute, Kolkata
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
github:
  github_url: https://www.github.com/pinakinathc